### ISSUE TITLE
FYI: This package can corrupt your python process' memory

### ISSUE THREAD

**Issue by tachim** [jakevdp/pypropack#8]
We were seeing some bizarre issues with malloc and memory corruption -- switching to sklearn's TruncatedSVD actually fixed them.

**Comment by jakevdp** [comment]
I believe it. I wouldn't really recommend this package to anyone.

**Comment by tachim** [comment]
ha fair enough

**Comment by jakevdp** [comment]
I've pushed a "fix" to the README: https://github.com/jakevdp/pypropack/commit/ea9b058cb870f2328eeaa5b66c6186b3067126bf
